apiVersion: v1
kind: ServiceAccount
metadata:
  name: guestbook-ui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guestbook-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld-service
